stages:
  - deploy

pages:
  stage: deploy
  script:
    - mkdir public
    - find . -not -path '*/\.*' -type f -exec mv '{}' public/ \;
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  only:
    - master
